### ISSUE TITLE
Travis build failure with mocha error

### ISSUE THREAD

**Issue by trystant** [trystant/dev-error-messages#14]
A student is running into this [error](https://travis-ci.org/ZaBAOW/blog-api-challenge-og) when running the build on Travis.

The specific error is:
```

**Comment by trystant** [comment]
It looks removing the `node_modules` directory and adding a Node based `.gitignore` to the [project](https://github.com/ZaBAOW/blog-api-challenge-og)

**Comment by trystant** [comment]
It looks like there are a couple of potentially related issues, but I'm not sure whether [6861](https://github.com/travis-ci/travis-ci/issues/6861), [8082](https://github.com/travis-ci/travis-ci/issues/8082) or another issue could be the source of the problem.

**Comment by trystant** [comment]
This build is hanging on Windows & Linux. When running this on the fork, the server hangs but with the following error:

```
ReferenceError: update is not defined
    at /home/mnyon/code/blog-api-challenge-og/test/blog-test.js:59:4
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by trystant** [comment]
@ZaBAOW for updates
