### ISSUE TITLE
Error installing database extensions

### ISSUE THREAD

**Issue by trystant** [trystant/dev-error-messages#28]
```
ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create extension "pg_trgm"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS "pg_trgm"
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:333:in `enable_extension'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:846:in `block in method_missing'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:815:in `block in say_with_time'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:815:in `say_with_time'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:835:in `method_missing'
/home/mnyon/code/Client2018/db/schema.rb:17:in `block in <top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/schema.rb:48:in `instance_eval'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/schema.rb:48:in `define'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/schema.rb:44:in `define'
/home/mnyon/code/Client2018/db/schema.rb:13:in `<top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:223:in `load_schema'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:253:in `block in load_schema_current'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:291:in `each'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:252:in `load_schema_current'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:260:in `block (3 levels) in <top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:264:in `block (3 levels) in <top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/bin/ruby_executable_hooks:15:in `eval'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
PG::InsufficientPrivilege: ERROR:  permission denied to create extension "pg_trgm"
HINT:  Must be superuser to create this extension.
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:333:in `enable_extension'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:846:in `block in method_missing'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:815:in `block in say_with_time'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:815:in `say_with_time'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/migration.rb:835:in `method_missing'
/home/mnyon/code/Client2018/db/schema.rb:17:in `block in <top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/schema.rb:48:in `instance_eval'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/schema.rb:48:in `define'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/schema.rb:44:in `define'
/home/mnyon/code/Client2018/db/schema.rb:13:in `<top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:223:in `load_schema'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:253:in `block in load_schema_current'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:291:in `each'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:252:in `load_schema_current'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:260:in `block (3 levels) in <top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:264:in `block (3 levels) in <top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/bin/ruby_executable_hooks:15:in `eval'
/home/mnyon/.rvm/gems/ruby-2.4.1@client/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by trystant** [comment]
This was resolved by combining `trust` authentication & specifying a db username.
