### ISSUE TITLE
`find_spec_for_exe': can't find gem google_maps_geocoder (>= 0.a) 

### ISSUE THREAD

**Issue by trystant** [trystant/dev-error-messages#8]
Ran into this error while deploying to a staging host for a client. This is the full message:

```
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem google_maps_geocoder (>= 0.a) (Gem::GemNotFoundException)
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by trystant** [comment]
Hmm...I see the same error when upgrading a library from ruby 2.4 to 2.5:
```
scorintha:~/workspace (master) $ bundle exec rake
Traceback (most recent call last):
        4: from /usr/local/rvm/gems/ruby-2.5.0@google_maps_geocoder/bin/ruby_executable_hooks:15:in `<main>'
        3: from /usr/local/rvm/gems/ruby-2.5.0@google_maps_geocoder/bin/ruby_executable_hooks:15:in `eval'
        2: from /usr/local/rvm/gems/ruby-2.5.0@google_maps_geocoder/bin/bundle:23:in `<main>'
        1: from /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem google_maps_geocoder (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```

**Comment by trystant** [comment]
It looks like the solution to this was to update Rubygems from `2.7.3` to `2.7.4`.
